using Newtonsoft.Json;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class otherGoal
    {
        public string id { get; set; }
        public string title { get; set; }
        public string snippit { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool isCompleted { get; set; }
        [JsonIgnore]
        public string categoryID { get; set; }
        [JsonProperty("categoryID")]
        private string CategoryID
        {
            // get is intentionally omitted here
            set { categoryID = value; }
        }
        [JsonIgnore]
        public virtual otherCategory otherCategory { get; set; }
    }
}