//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class otherGoal
    {
        public string Id { get; set; }
        public string title { get; set; }
        public string snippit { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool isCompleted { get; set; }
        public string categoryID { get; set; }
    
        public virtual otherCategory otherCategory { get; set; }
    }
}
