//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class userModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime Lastlogin { get; set; }
        public int OtherDB { get; set; }
    }
}
