//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersEntities : DbContext
    {
        public UsersEntities()
            : base("name=UsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<trueFalseArr> trueFalseArrs { get; set; }
        public virtual DbSet<completedDaily> completedDailies { get; set; }
        public virtual DbSet<otherGoal> otherGoals { get; set; }
        public virtual DbSet<otherCategory> otherCategories { get; set; }
        public virtual DbSet<dailyGoal> dailyGoals { get; set; }
    }
}
